config/routes.rb
Rails.application.routes.draw do
  resources :search, only: :index

  root "search#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider_cache.rb
class ProviderCache < ApplicationRecord
  validates :npi, presence: true, uniqueness: { case_sensitive: false }

  has_many :addresses, class_name: 'ProvidersCaches::Address'
  has_many :taxonomies, class_name: 'ProvidersCaches::Taxonomy'

  accepts_nested_attributes_for :addresses, :taxonomies

  scope :optimized_collection, -> {   joins(:addresses, :taxonomies)
                                 .includes(:addresses, :taxonomies)
                                 .order(created_at: :desc)
  }

  def main_address
    addresses.first
  end

  def main_taxonomy
    taxonomies.first
  end
end

app/models/providers_caches.rb
module ProvidersCaches
  def self.table_name_prefix
    "providers_cache_"
  end
end

app/models/providers_caches/address.rb
module ProvidersCaches
  class Address < ApplicationRecord
    belongs_to :provider_cache
  end
end

app/models/providers_caches/taxonomy.rb
module ProvidersCaches
  class Taxonomy < ApplicationRecord
    belongs_to :provider_cache
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
require "np_registry/provider_search"

class SearchController < ApplicationController
  before_action :load_cache
  rescue_from RuntimeError do |e|
    flash[:alert] = e.message
    redirect_to root_path
  end

  def index
  end

  private

  def load_cache
    @result = ProviderCache.optimized_collection

    return if search_params[:search_key].nil?

    @search_key = search_params[:search_key]
    check_search_key

    if provider_not_found
      cached_provider = import_provider
      @result = [cached_provider] + @result.to_a
      @result.flatten!
    end

    flash[:notice] = "Provider found!"
  end

  def search_params
    params.permit :search_key
  end

  def check_search_key
    raise "Invalid NPI. Please insert only numbers." if @search_key.match? /[^0-9]/
  end

  def provider_not_found
    @result.none? { |provider| provider.npi.eql? @search_key }
  end

  def import_provider
    ProviderSearch.new(search_key: @search_key).import_provider
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CMT Solutions - Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/search/index.html.erb
<div class="w-full text-center">
  <h1 class="text-2xl">National Provider Identifier Search</h1>

  <div class="w-full mt-4 p-6 shadow-lg rounded-lg border border-slate-50" data-controller="search-form">
    <%= toastr_flash %>

    <%= form_with url: search_index_path, method: :get, class: 'flex items-center justify-center',
                  html: {
                    'data-search-form-target': 'form',
                    'data-action': 'submit->search-form#searchKeyValidation'
                  } do |form|%>
      <%= form.text_field :search_key, placeholder: 'NPI', class: 'rounded-full border-slate-300', 'data-search-form-target': 'searchKey'%>

      <%= form.button 'Search',
                      class: 'ml-2 bg-blue-500 text-white w-max p-2 rounded-lg h-9 w-14 flex items-center justify-center shadow-md' do %>
        <%= image_tag 'icons/search', size: '20x20' %>
      <% end %>
    <% end %>

    <div id="results" class="w-full mt-12 mb-8">
      <table class="table-auto w-full">
        <thead class="text-slate-700">
          <tr>
            <th>NPI</th>
            <th>Name</th>
            <th>Address</th>
            <th>Address Type</th>
            <th>Taxonomy</th>
          </tr>
        </thead>

        <tbody>
          <% @result.each do |provider|  %>
            <tr>
              <td><%= provider.npi %></td>
              <td><%= provider.name %></td>
              <td><%= provider.main_address.address %></td>
              <td><%= provider.main_address.address_type %></td>
              <td><%= provider.main_taxonomy.desc %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <% if @result.empty? %>
      <span class="text-lg"> There's no records to show. </span>
    <% end %>
  </div>
</div>